import {
  LEADERBOARD_AVATAR_APPEAR_TIME,
  LEADERBOARD_AVATAR_GAP_DURATION,
  LEADERBOARD_AVATAR_APPEAR_DURATION,
  LEADERBOARD_ASSET_MOVE_OUT_TIME,
  LEADERBOARD_ASSET_MOVE_OUT_DURATION,
} from "../../constants/constants";
import { useEasingOutCubicFunction } from "./use_easing_sin_function";

export const useAvatarListAnimation = () => {
  const position = [1300, 850, 850, 1300];

  const moveFirstAvatar = useEasingOutCubicFunction(
    [
      LEADERBOARD_AVATAR_APPEAR_TIME,
      LEADERBOARD_AVATAR_APPEAR_TIME + LEADERBOARD_AVATAR_APPEAR_DURATION,
      LEADERBOARD_ASSET_MOVE_OUT_TIME,
      LEADERBOARD_ASSET_MOVE_OUT_TIME + LEADERBOARD_ASSET_MOVE_OUT_DURATION,
    ],
    position
  );

  const moveSecondAvatar = useEasingOutCubicFunction(
    [
      LEADERBOARD_AVATAR_APPEAR_TIME + LEADERBOARD_AVATAR_GAP_DURATION,
      LEADERBOARD_AVATAR_APPEAR_TIME +
        LEADERBOARD_AVATAR_APPEAR_DURATION +
        LEADERBOARD_AVATAR_GAP_DURATION,
      LEADERBOARD_ASSET_MOVE_OUT_TIME,
      LEADERBOARD_ASSET_MOVE_OUT_TIME + LEADERBOARD_ASSET_MOVE_OUT_DURATION,
    ],
    position
  );

  const moveThirdAvatar = useEasingOutCubicFunction(
    [
      LEADERBOARD_AVATAR_APPEAR_TIME + LEADERBOARD_AVATAR_GAP_DURATION * 2,
      LEADERBOARD_AVATAR_APPEAR_TIME +
        LEADERBOARD_AVATAR_APPEAR_DURATION +
        LEADERBOARD_AVATAR_GAP_DURATION * 2,
      LEADERBOARD_ASSET_MOVE_OUT_TIME,
      LEADERBOARD_ASSET_MOVE_OUT_TIME + LEADERBOARD_ASSET_MOVE_OUT_DURATION,
    ],
    position
  );

  const moveForthAvatar = useEasingOutCubicFunction(
    [
      LEADERBOARD_AVATAR_APPEAR_TIME + LEADERBOARD_AVATAR_GAP_DURATION * 3,
      LEADERBOARD_AVATAR_APPEAR_TIME +
        LEADERBOARD_AVATAR_APPEAR_DURATION +
        LEADERBOARD_AVATAR_GAP_DURATION * 3,
      LEADERBOARD_ASSET_MOVE_OUT_TIME,
      LEADERBOARD_ASSET_MOVE_OUT_TIME + LEADERBOARD_ASSET_MOVE_OUT_DURATION,
    ],
    position
  );

  return {
    moveFirstAvatar,
    moveSecondAvatar,
    moveThirdAvatar,
    moveForthAvatar,
  };
};
